// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CampaignClaimed, CampaignClaimedTableId } from "./tables/CampaignClaimed.sol";
import { OwnedSlots, OwnedSlotsData, OwnedSlotsTableId } from "./tables/OwnedSlots.sol";
import { OwnedTraits, OwnedTraitsData, OwnedTraitsTableId } from "./tables/OwnedTraits.sol";
import { MascotSystemSettings, MascotSystemSettingsData, MascotSystemSettingsTableId } from "./tables/MascotSystemSettings.sol";
import { MascotTraitChanges, MascotTraitChangesData, MascotTraitChangesTableId } from "./tables/MascotTraitChanges.sol";
import { MascotSlotChanges, MascotSlotChangesTableId } from "./tables/MascotSlotChanges.sol";
import { Mascot, MascotData, MascotTableId } from "./tables/Mascot.sol";
import { Slot, SlotData, SlotTableId } from "./tables/Slot.sol";
import { Trait, TraitData, TraitTableId } from "./tables/Trait.sol";
import { UserMascots, UserMascotsTableId } from "./tables/UserMascots.sol";
import { BaseCosmetic, BaseCosmeticData, BaseCosmeticTableId } from "./tables/BaseCosmetic.sol";
import { RatioConfig, RatioConfigData, RatioConfigTableId } from "./tables/RatioConfig.sol";
import { ItemSellerERC20, ItemSellerERC20Data, ItemSellerERC20TableId } from "./tables/ItemSellerERC20.sol";
import { ItemPrice, ItemPriceData, ItemPriceTableId } from "./tables/ItemPrice.sol";
import { GateKeeperConfig, GateKeeperConfigData, GateKeeperConfigTableId } from "./tables/GateKeeperConfig.sol";
