// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemPriceData } from "./../tables/ItemPrice.sol";
import { ItemSellerERC20Data } from "./../tables/ItemSellerERC20.sol";

/**
 * @title IItemSeller
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemSeller {
  function kalb_v14__registerERC20Token(uint256 smartObjectId, address tokenAddress, address receiver) external;

  function kalb_v14__updateERC20Receiver(uint256 smartObjectId, address receiver) external;

  function kalb_v14__setItemPrice(uint256 smartObjectId, uint256 inventoryItemId, uint256 price) external;

  function kalb_v14__unsetItemPrice(uint256 smartObjectId, uint256 inventoryItemId) external;

  function kalb_v14__purchaseItem(uint256 smartObjectId, uint256 inventoryItemId, uint256 quantity) external;

  function kalb_v14__collectTokens(uint256 smartObjectId) external;

  function kalb_v14__getItemPriceData(
    uint256 smartObjectId,
    uint256 inventoryItemId
  ) external returns (ItemPriceData memory);

  function kalb_v14__getERC20Data(uint256 smartObjectId) external returns (ItemSellerERC20Data memory);

  function kalb_v14__getContractAddress() external returns (address);
}
