// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IMascotCreator } from "./IMascotCreator.sol";
import { IMascotManager } from "./IMascotManager.sol";
import { ISquareBaseSystem } from "./ISquareBaseSystem.sol";
import { IMascotSystem } from "./IMascotSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is IBaseWorld, IMascotCreator, IMascotManager, ISquareBaseSystem, IMascotSystem {

}
